### ISSUE TITLE
Is there a way to run this headless? 

### ISSUE THREAD

**Issue by vihaanmisra** [FlyCole/Dream2Real#1]
I was trying to run this on my server, the set up worked nicely and I tried to set up a open3d web_visualizer but ran into a thread of issues. Is there any way to run this headless and probably store a video of the output instead?

**Comment by FlyCole** [comment]
Hi, thanks for your interest in our work. Regarding the issue you mentioned, I think it might be an Open3D issue since in our project there's no such requirement to make it headless. However, here's some tutorial about how to convert to headless mode in Open3D https://www.open3d.org/docs/latest/tutorial/Advanced/headless_rendering.html. You are welcome if you would like to open a pull request for this!
